### ISSUE TITLE
test failures with recent builds of chrome

### ISSUE THREAD

**Issue by Spongman** [shellscape/mocha-chrome#32]
i'm getting test failures when running with a recent build of chrome (>=71):

```
> npm run bdd

> mocha-chrome@1.1.0 bdd E:\play\mocha-chrome
> mocha test/test.js --timeout 10000 --exit



  MochaChrome
Mocha-Chrome Failed: mocha was not found in the page within 1000ms of the page loading.
Mocha-Chrome Failed: mocha.run() was not called within 1000ms of the page loading.
    √ fails if mocha isn't loaded (2527ms)
Mocha-Chrome Failed: mocha.run() was not called within 1000ms of the page loading.
    √ fails if mocha.run isn't called (2448ms)
Promise Rejection:  Error: No inspectable targets
    at defaultTarget (E:\play\mocha-chrome\node_modules\chrome-remote-interface\lib\chrome.js:46:23)
    at E:\play\mocha-chrome\node_modules\chrome-remote-interface\lib\chrome.js:232:32
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
    1) runs a test
    √ reports a failure (1408ms)
    √ allows runner modification (1379ms)
    √ supports different reporters (1412ms)
    √ supports mixed tests (1647ms)
    √ reports async failures (1466ms)
    √ supports test using and clearing localStorage (1223ms)
    √ handles circular structures in console.log (1042ms)

  mocha-chrome binary
    √ should report version (1243ms)
    √ should run a successful test (1954ms)
    √ should run a failing test (2335ms)
    √ should default to "spec" reporter (2227ms)
    √ should honor --spec parameter (2207ms)
    √ should allow use of --chrome-flags (2243ms)
    √ should use the --timeout flag value (3752ms)


  16 passing (43s)
  1 failing

  1) MochaChrome
       runs a test:
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by shellscape** [comment]
Thanks for creating an issue. I don't actually use or work on this module much anymore. If you'd like to contribute a fix for this and help maintain it moving forward, that'd be cool. You might also have a look at https://www.npmjs.com/package/mocha-puppeteer, which aims to accomplish something similar.

**Comment by gamtiq** [comment]
It seems this problem is related to https://github.com/GoogleChrome/chrome-launcher/issues/145.
Probably it can be fixed by using `connectionPollInterval` option of `chrome-launcher`.
