### ISSUE TITLE
Unexpected token function

### ISSUE THREAD

**Issue by kettanaito** [shellscape/mocha-chrome#9]
> Please note that this template is not optional. If you proceed with this form,
please fill out **_all_** fields, or your issue may be closed as "invalid."
Please do not delete this template. Please do remove this header to acknowledge this message.

* Operating System: MacOS Sierra (10.12.6 (16G29)
* Node Version: 6.9.5
* NPM Version: 5.4.1
* mocha Version: 3.5.0
* mocha-chrome Version: 0.2.1

- [ ] This is a **feature** request
- [x] This is a **bug**

### Code

**foo.spec.js:**
```js
describe('Tracker', () => {
  it('Should do two', () => {
    const element = document.createElement('div');
    element.style.width = 500;
    element.style.height = 500;
    document.body.appendChild(element);

    console.log(element.getBoundingClientRect());
    return true;
  });
});
```

**index.html:**
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Tests</title>
  <link rel="stylesheet" href="../node_modules/mocha/mocha.css" />
</head>
<body>
  <div id="mocha"></div>
  <script src="../node_modules/mocha/mocha.js"></script>
  <script src="../node_modules/chai/chai.js"></script>
  <script>
    mocha.ui('bdd');
    mocha.reporter('html');
    var expect = chai.expect;
  </script>

  <!-- Library -->
  <script src="../lib/index.js"></script>

  <!-- Tests -->
  <script src="./foo.spec.js"></script>

  <script>
    mocha.run();
  </script>
</body>
</html>
```

**Run:**
```
node_modules/mocha-chrome/bin/mocha-chrome test/index.html
```
Executing just `mocha-chrome` after global installation produces the same error, as `mocha-chrome` command executes the bin file provided in the example above.

### Expected Behavior
Tests should run.

### Actual Behavior
Error in the console trying executing the test command:
```
/Users/azakharchenko/Local/Libraries/sentinel-dom/node_modules/mocha-chrome/bin/mocha-chrome:89
(async function run () {
       ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.j
```

**Comment by shellscape** [comment]
@kettanaito https://github.com/shellscape/mocha-chrome/blob/master/package.json#L15
